SB-Title: "HideOrHunt" # Scoreboard TitleC

Join-Title: "Welcome" # Player Join Title

WorldBorder: 200 # sets the worldborder from the location of the player who starts the game! DIAMETER !

# allows the op player to play the game!
Allow-Op: true

Ban-Player-On-Death: true # BAns the player on death

Inventory-Keep: 20 # Inventory keep chance! Compared out of 100. keep 0 for disabling it!

Player-Coord-Chance: 10 # Gives the killer of a player his beacon coords! Compared out of 100. Keep 0 for disabling it!

# Normal kits
# Do not add beacon into it!
Kits:
  - STONE_PICKAXE, 1
  - STONE_AXE, 1
  - STONE_SHOVEL, 1
  - BREAD, 32

# Potions that will be given to the player!
# https://minecraftitemids.com/types/potion
# Use the above link to get the item id with ease and sprecify the number of items you would like to get!
Kits-Potion:
  - minecraft:potion{Potion:long_invisibility} 1 # 1 represents the number of potions

Rules-Messages:
  - "&4Rules"
  - "&2Your Rules"

Auto-Episodes: true
Grace-Period: true # Enable / Disable Grace Period
Episode-Time: 30 # Grace period duration. In minutes!
Episode-End-Break-Time: 60 # Break time when a episode ends! In seconds. Set it to 0 to disable it

Auto-Supply-Drops: true
Supply-Drop-Delay: 10 # Delay between supply drops in minutes
Supply-Drop-Items:
  1:
    - STEAK, 32
    - BOW, 1
  2:
   - WHITE_WOOL, 1
# The plugin will pick any one combination of items between 1 and 2 from the above example. You can have unlimited amount of combinations!
# You can even use AIR to make the chest look better but thats all up to you.
Disable-Other-Worlds: true # Disables nether and end
Pvp-Log: 10 # Pvp log timer. Set 0 to disable it

Custom-Tab-List: true # Enable / Disable tab list! Only works for 1.16
Tab-List-Title: "&4Hide Or Hunt" # use \n to add multiple lines. Example : "&4Hide Or Hunt\nEnjoy"
Tab-List-Footer: "&Enjoy\nYou are playing on mc.Test.server" 

Team-Damage: false # On or off team damage 

# %message%
# %playername%
# %playerteam%
Main-Chat-Format: "[Main]]%playerteam%%playername%%message%"
Team-Chat-Format: "[TeamChat]%playerteam%%playername%%message%"
