name: HideOrHunt
main: me.latestion.hoh.HideOrHunt
author: Latestion
version: ${project.version}
api-version: 1.13
authors: [Latestion, barpec12]
website: https://latestion.github.io/
description: ${project.description}
commands:
  HOH: