name: HideOrHunt
main: me.latestion.hoh.HideOrHunt
version: ${project.version}
api-version: 1.13
authors: [Latestion, barpec12]
website: https://latestion.github.io/
description: ${project.description}
commands:
  HOH:
    description: all hide or hunt commands
    aliases: [hideorhunt]
permissions:
  hoh.*:
    description: HOH parent permission node
    default: op
    children:
      hoh.start:
        description: start games
      hoh.stop:
        description: stop games
      hoh.freeze:
        description: temporarily pause games
      hoh.reload:
        description: reload the config.yml
      hoh.beacon:
        description: teleport to players' beacons
      hoh.spy:
        description: view other teams' private chats
      hoh.craft:
        description: enable / disable crafting tables
      hoh.continue:
        description: continues previous game